import os

print(os.getcwd())
# os.chdir("C:/Temp")
# print(os.getcwd())
# os.mkdir("test_folder")
print(os.name)
# open("hello.txt", "w").close()
# os.remove("hello.txt")
# os.rename("hello.txt", "hello_python.txt")
os.makedirs("test_folder", exist_ok=True)
print(os.environ["PATH"])
print(os.path.exists("hello.txt"))
print(os.path.getsize("hello.txt"))
print(os.path.getctime("hello.txt"))
print(os.path.abspath("hello.txt"))
print(os.path.isdir("hello.txt"))
print(os.path.isfile("hello.txt"))
print(os.cpu_count())
